package org.now.terminal.shared.kernel

/**
 * Domain Message - Encapsulates various messages generated by the domain layer
 */
data class DomainMessage(
    val key: String,
    val message: String,
    val type: MessageType = MessageType.ERROR,
    val params: Map<String, Any> = emptyMap()
) {
    /**
     * Get formatted message (supports parameter substitution)
     */
    fun getFormattedMessage(): String {
        var formatted = message
        params.forEach { (key, value) ->
            formatted = formatted.replace("{$key}", value.toString())
        }
        return formatted
    }
    
    override fun toString(): String = getFormattedMessage()
}